/**
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * @since 0.1.5
 */
package g002;

/**
 * Liddle: main description hee
 * 
 * @author Marcus
 * @version 0.1.5
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
